### PR TITLE
Fixes syntax error on developer mode installer when trying to fetch from Chromium Dash

### PR DESCRIPTION
**Pull request by kosuke14**
I got an error when retrieving image download URL from Chromium Dash, so I modified the part that fetches builds.
image

### CODE REVIEW

**Review by rainestorme — CHANGES_REQUESTED** [review]
That's all solid, but `-k` is neccesary on some enterprise networks to bypass issues with self-signed certs.

**Comment by plooshi** [comment]
all you need is the \\ removed for it to work

**Comment by kosuke14** [comment]
I've re-added `-ks` option.

**Review by rainestorme — APPROVED** [review]
LGTM.

**Pull request merged**
