### PR TITLE
put bit.ly link in readme to make typing the link in vt2 more reasonable

### PR DESCRIPTION
**Pull request by OtterCodes101**

### CODE REVIEW

**Comment by rainestorme** [comment]
I don't have a test device on-hand right now, can you confirm that this works?

**Comment by rainestorme** [comment]
Also I'm about to push a big documentation update, you might want to wait until after that to update your PR.

**Comment by OtterCodes101** [comment]
Yup, just confirmed it works.

**Comment by rainestorme** [comment]
Alright. I'll just do a bit of testing to ensure security, give me a minute.

**Comment by rainestorme** [comment]
Yep, everything looks fine.

**Pull request merged**
