### PR TITLE
Fixes get_largest_cros_blockdev and others on mush

### PR DESCRIPTION
**Pull request by kosuke14**
Reverted to get_largest_nvme_namespace because the new one doesn't return anything on mush environment (on my chromebook's).

### CODE REVIEW

**Comment by kosuke14** [comment]
Added get_largest_cros_blockdev back, and fixes.

**Comment by rainestorme** [comment]
What doesn't work on your system? Can you add debugging to get_largest_cros_blockdev and try running it interactively to see where it breaks?

**Comment by kosuke14** [comment]
I made a script like in the images.
With root, it works correctly but without root, it won't work correctly.
IMG_3823
IMG_3821

**Comment by kosuke14** [comment]
sfdisk in get_largest_cros_blockdev required root.

**Comment by rainestorme** [comment]
You modified get_largest_cros_blockdev to use doas - does get_largest_cros_blockdev consistently work now? Or should it be reverted bak to get_largest_nvme_namespace entirely?

**Comment by kosuke14** [comment]
get_largest_cros_blockdev with doas works now.
I've tested on my Chromebook.

**Comment by rainestorme** [comment]
I can't seem to commit to your branch directly, so here's a patch that I would like applied before I merge this.
[0001-revert-Bring-back-get_largest_cros_blockdev-in-mush.patch](https://github.com/user-attachments/files/18253107/0001-revert-Bring-back-get_largest_cros_blockdev-in-mush.patch)

**Comment by rainestorme** [comment]
LGTM!

**Pull request merged**
