### PR TITLE
Fixing finding an open loop device (closes #102)

### LINKED ISSUE #102: /dev/loop14: failed to set up loop device: No such file or directory
**Describe the bug**
While installing I get this error along with the following line: "losetup
-P $loop" "$bin"" command failed with exit code 1.

**To Reproduce**
1. I just installed it, it worked on a different chromebook though so idk

**Expected behavior**
it to be installed

**Screenshots**
its after the losetup: /dev/FINDING FREE!!!

**System (please complete the following information):**
 - Board dedede
 - Version i've tried every version
- Installation method used idk what this means i just used vt2

**Additional context**

### PR DESCRIPTION
**Pull request by Packjackisback**
Just added a head -1 to the losetup -f

### CODE REVIEW

**Comment by Packjackisback** [comment]
My bad for the formatting changes, you can definitely revert those

**Comment by rainestorme** [comment]
Looks like a fine solution. Have you tested at all?

**Comment by Packjackisback** [comment]
Worked when I tested, could be tested further definitely.

**Comment by Packjackisback** [comment]
This should also work on older versions with the usual losetup behaviour because it just gets the last line.

**Comment by Packjackisback** [comment]
Yeah np, I had a quiz to deal with.

**Pull request closed without merging**
